---
  - name: config Web VM with Docker
    hosts: ELK
    become: true
    tasks:

    - name: docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present

    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present

    - name: install docker python module
      pip:
       name: docker
       state: present

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
